fails:Executing break from within a block returns from the invoking singleton method
fails:Executing break from within a block returns from the invoking method with the argument to break
fails:Executing break from within a block returns from the original invoking method even in case of chained calls
