fails:Kernel.fail is a private method
fails:Kernel.fail raises a RuntimeError